### ISSUE TITLE
Script fails on 64bit arm

### ISSUE THREAD

**Issue by AlinaNova21** [benweissmann/getmic.ro#2]
On my Pine64 running ubuntu the getmic.ro script downloads linux64 rather than linux-arm.
This seems to be due to it checking for *"64" and getting confused.
```bash
$ uname -m
aarch64
```

**Comment by Calinou** [comment]
See also https://github.com/zyedidia/micro/issues/1170 (that one should probably be closed as it's not related to micro itself).
