### ISSUE TITLE
update-alternatives addition breaks non-interactive use

### ISSUE THREAD

**Issue by gdevenyi** [benweissmann/getmic.ro#29]
The recent addition of the update-alternatives functionality has broken the script as fire-and-forget.

**Comment by benweissmann** [comment]
The script should detect when it's running without a TTY and skip asking about update-alternatives -- are you seeing something different? Could you post the output you're getting, and some more details about your environment?

**Comment by fgardt** [comment]
Using `curl https://getmic.ro | GETMICRO_REGISTER=y sh` as the script suggests gets rid of the prompt but the bigger issue is that if you want to use update-alternatives it doesn't work at all. See #30.

**Comment by gdevenyi** [comment]
> Using `curl https://getmic.ro | GETMICRO_REGISTER=y sh` as the script suggests gets rid of the prompt but the bigger issue is that if you want to use update-alternatives it doesn't work at all. See #30.

Changing the way it runs is a breaking change.

**Comment by gdevenyi** [comment]
> The script should detect when it's running without a TTY and skip asking about update-alternatives -- are you seeing something different? Could you post the output you're getting, and some more details about your environment?

I didn't say without a TTY, but rather its no longer, copy+paste, and get micro installed with no interruptions.

**Comment by benweissmann** [comment]
Hey all -- https://github.com/benweissmann/getmic.ro/pull/31 is in the process of getting merged and we can continue any discussion about that fix on that thread.

`getmic.ro` doesn't guarantee that there will never be changes in behavior. I've gotten a number of requests over time to add `update-alternatives` support; it's probably been the most-requested feature. There's not really a way to add functionality like this without either burying it or adding *some* behavior change, and I think the approach of defaulting to the old behavior in a non-interactive context but prompting in an interactive context is a relatively conservative one. If you'd like an installation method that's even more conservative, I'd recommend installing micro from your system's package manager.
