### ISSUE TITLE
Can't install micro on Haiku OS.

### ISSUE THREAD

**Issue by jeremypass96** [benweissmann/getmic.ro#34]
![screenshot1](https://user-images.githubusercontent.com/31392377/202864136-1958299c-c419-4901-9a4e-168d86de3eac.png)

**Comment by anonyco** [comment]
Micro currently does not support haiku is

open an issue here: https://github.com/zyedidia/micro/issues

there currently doesn’t seem to be any mention of haiku os in micro so see if you can strum up support for it

**Comment by benweissmann** [comment]
Closing this (this repo is just for the curl|bash installer); feel free to submit an upstream issue about adding support for Haiku to Micro!
