### ISSUE TITLE
Support nightly install?

### ISSUE THREAD

**Issue by gdevenyi** [benweissmann/getmic.ro#35]
The nightly build is available here:
https://github.com/zyedidia/micro/releases/tag/nightly

It would be nice to have an export option to download and install it

**Comment by staticfrost** [comment]
I agree

**Comment by benweissmann** [comment]
Nightly releases can be installed from that link by downloading the zip/tar.gz. For simplicity's sake, I'm not planning to support an option for nightly install from the curl|bash installer.
