### ISSUE TITLE
Check if latest tag is newer than installed version before attempting to install

### ISSUE THREAD

**Issue by gdevenyi** [benweissmann/getmic.ro#36]
If the latest version of micro is installed, a new one probably shouldn't be downloaded.

I currently do this to check to handle it externally.

```bash
ver () { echo "$@" | awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'; }
if [[ $(ver $(micro --version | head -1 | awk '{print $2}')) -lt $(ver $(curl --silent "https://api.github.com/repos/zyedidia/micro/releases/latest" | grep tag_name | grep -Eo '([0-9]{1,}\.)+[0-9]{1,}')) ]]; then
    (mkdir -p ${HOME}/bin && cd ${HOME}/bin && curl https://getmic.ro | bash &>/dev/null)
fi
```

**Comment by benweissmann** [comment]
Given the setup of this installer, there's no safe way to check the current version of micro: your script runs `micro --version`, which assumes that there's a binary called `micro` in the current directory or `$PATH`, and that it's the micro editor and not some other program called `micro` (I don't think micro is quite popular enough to make the assumption that no other program could be called micro, unlike the other utilities used by the script currently, which are all shell builtins, extremely common programs such as `curl`, or POSIX-specified commands). I don't think it's a good idea, from a reliability or security standpoint, to make assumptions about a local binary called `micro`.
