### ISSUE TITLE
`curl` triggers a 301 moved permanently

### ISSUE THREAD

**Issue by rxu18** [benweissmann/getmic.ro#9]
Tested with AWS Linux machine and WSL instance.

The call `curl getmic.ro` results in a 301 message below. wget and accessing with a browser still works.

```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>
```

**Comment by zyedidia** [comment]
Make sure you run exactly `curl https://getmic.ro` (don't drop the `https://`).

**Comment by rxu18** [comment]
Thanks!
